name: nano_design_system
description: Nano design tokens and shared UI primitives
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.2

resolution: workspace
dependencies:
  flutter:
    sdk: flutter
  nano_domain:
    path: ../nano_domain
  nano_media:
    path: ../nano_media

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
