name: nano_media
description: Nano nano_media package
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.2

resolution: workspace
dependencies:
  nano_domain:
    path: ../nano_domain

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
